spring:
  application:
    name: news-service
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/test_db
  liquibase:
    change-log: db.changelog/changelog-master.xml
    enabled: true
    contexts: test
  jpa:
    show-sql: true

server:
  port: 8081